CREATE DATABASE IF NOT EXISTS lanonna;
USE lanonna;

CREATE TABLE IF NOT EXISTS productos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL,
  descripcion TEXT NOT NULL,
  precio DECIMAL(10,2) NOT NULL,
  categoria VARCHAR(80) NOT NULL,
  imagen VARCHAR(255)
);
